services:
  db:
    image: postgres:13
    container_name: bnpl-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: bnpl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bnpl_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bnpl-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bnpl_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: